#pragma once

#ifndef APP_WIFI_PROV_TYPE_BLE
#define APP_WIFI_PROV_TYPE_BLE CONFIG_APP_WIFI_PROV_TYPE_BLE
#endif

#ifndef APP_WIFI_PROV_TYPE_SOFT_AP
#define APP_WIFI_PROV_TYPE_SOFT_AP CONFIG_APP_WIFI_PROV_TYPE_SOFT_AP
#endif

#ifndef APP_WIFI_PROV_TIMEOUT_S
#define APP_WIFI_PROV_TIMEOUT_S CONFIG_APP_WIFI_PROV_TIMEOUT_S
#endif

#ifndef APP_WIFI_PROV_TRANSPORT
/**
 * @brief Transport type string. Either "ble" or "softap".
 */
#define APP_WIFI_PROV_TRANSPORT CONFIG_APP_WIFI_PROV_TRANSPORT
#endif

#define APP_WIFI_QRCODE_URL CONFIG_APP_WIFI_QRCODE_URL
