#pragma once

#ifndef APP_WIFI_PROV_TYPE_BLE
#define APP_WIFI_PROV_TYPE_BLE CONFIG_APP_WIFI_PROV_TYPE_BLE
#endif

#ifndef APP_WIFI_PROV_TYPE_SOFT_AP
#define APP_WIFI_PROV_TYPE_SOFT_AP CONFIG_APP_WIFI_PROV_TYPE_SOFT_AP
#endif

#ifndef APP_WIFI_PROV_TIMEOUT_S
#define APP_WIFI_PROV_TIMEOUT_S CONFIG_APP_WIFI_PROV_TIMEOUT_S
#endif
