#pragma once

#ifndef AUTO_WIFI_PROV_TYPE_BLE
#define AUTO_WIFI_PROV_TYPE_BLE CONFIG_AUTO_WIFI_PROV_TYPE_BLE
#endif

#ifndef AUTO_WIFI_PROV_TYPE_SOFT_AP
#define AUTO_WIFI_PROV_TYPE_SOFT_AP CONFIG_AUTO_WIFI_PROV_TYPE_SOFT_AP
#endif

#ifndef AUTO_WIFI_PROV_TIMEOUT_S
#define AUTO_WIFI_PROV_TIMEOUT_S CONFIG_AUTO_WIFI_PROV_TIMEOUT_S
#endif

#ifndef AUTO_WIFI_PROV_TRANSPORT
/**
 * @brief Transport type string. Either "ble" or "softap".
 */
#define AUTO_WIFI_PROV_TRANSPORT CONFIG_AUTO_WIFI_PROV_TRANSPORT
#endif

#ifndef AUTO_WIFI_PROV_QRCODE_URL
#define AUTO_WIFI_PROV_QRCODE_URL CONFIG_AUTO_WIFI_PROV_QRCODE_URL
#endif
